<li><a href='[field:arcurl/]' style="width: 285px">• [field:title/]</a>
                                <a style="width: 30px" href='[field:arcurl/]'>
                                    [field:isdeceipt]
                                    if (@me)
                                    {
                                        @me="aa";
                                    }
                                    [/field:isdeceipt]

                                </a>
                                <span style="color:#A2A4AD; ">[field:pubdate function='strftime("%m-%d",@me)'/]</span>
                            </li>