<?php
$z[0]=Array("arcurl","",13,28);
$z[1]=Array("title","",55,69);
$z[2]=Array("arcurl","",136,151);
$z[3]=Array("isdeceipt","\r\n                                    if (@me)\r\n                                    {\r\n                                        @me=\"aa\";\r\n                                    }\r\n                                    ",191,439);
$z[4]=Array("pubdate","",543,592);
$z[4][4]['function']="strftime(\"%m-%d\",@me)";

?>