<li class="tztbli"><a style="width: 250px"href='[field:arcurl/]'>• [field:title/]</a>
                                <a style="width: 30px" href='[field:arcurl/]'>
                                    [field:id  function="GetSignForInfos(‘uname’,@me)"/]
                                </a>

                                <span style="color:#A2A4AD; ">[field:pubdate function='strftime("%m-%d",@me)'/]</span>
                            </li>