<li style=" width:130px;height:180px;margin: 0px"><a href="[field:arcurl /]"
                                                                            title="[field:title /]">
                            <img
                                    src="[field:litpic /]" alt="[field:title /]"
                                    style=" width:100%; height:180px;border-radius: 5px;"/></a>
                        </li>