<li style="height:100px;" >
          <div style="border-bottom: 1px dashed #b3b3b3;padding: 5px;">
            <img src="[field:litpic/]" style="float:left; margin-top:5px; margin-right:5px;width:130px;height:170px;"/>
            <a  href='[field:arcurl/]'>
              [field:title/]
            </a>
            <span style="float: right; color:#999999;">[field:pubdate function='strftime("20%y-%m-%d",@me)'/]</span>

          </div>
       </li>