<?php
$z[0]=Array("litpic","",124,139);
$z[1]=Array("arcurl","",245,260);
$z[2]=Array("title","",278,292);
$z[3]=Array("pubdate","",367,421);
$z[3][4]['function']="strftime(\"20%y-%m-%d\",@me)";
$z[4]=Array("id","",446,502);
$z[4][4]['function']="GetSignForInfos(‘uname’,@me)";
$z[5]=Array("arcurl","",544,559);
$z[6]=Array("body","",641,695);
$z[6][4]['function']="cn_substr(html2text(@me),350)";

?>