<li class="tztbli"><a style="width: 250px;margin: 0;padding: 0" href='[field:arcurl/]' target='_blank'>•
                                [field:title/]</a>
                                <span style="color:#A2A4AD;margin-left: 3px; ">[field:pubdate function='strftime("%m-%d",@me)'/]</span>
                                [field:id function="GetSignForInfos(‘uname’,@me)"/]

                            </li>