<?php
$z[0]=Array("litpic","",124,139);
$z[1]=Array("arcurl","",220,235);
$z[2]=Array("title","",253,267);
$z[3]=Array("pubdate","",342,396);
$z[3][4]['function']="strftime(\"20%y-%m-%d\",@me)";
$z[4]=Array("id","",421,477);
$z[4][4]['function']="GetSignForInfos(‘uname’,@me)";
$z[5]=Array("arcurl","",519,534);
$z[6]=Array("body","",616,670);
$z[6][4]['function']="cn_substr(html2text(@me),350)";

?>