<li style=" width:90px;height:120px;margin: 0px"><a href="[field:arcurl /]"
                                                                            title="[field:title /]">
                            <img
                                    src="[field:litpic /]" alt="[field:title /]"
                                    style=" width:100%; height:120px;border-radius: 5px;"/></a>
                        </li>