<li  style="height:240px;float:left;margin-left: 25px">
          <div style="">
            <a style="display: block;text-align: center" href='[field:arcurl/]'>
              <img src="[field:litpic/]" style="margin-top:5px; margin-right:5px;width:130px;height:170px;"/>

              <div style="display: block;padding-top:10px;text-align: center">[field:title/]</div>
            </a>

          </div>
       </li>