<li class="tztbli"><a href='[field:arcurl/]'>• [field:title/]</a>
                                <a style="width: 30px" href='[field:arcurl/]'>
                                    [field:id  function="GetSignForInfos(‘uname’,@me)"/]
                                </a>
                                <a style="width: 30px;margin-left: 5px" href='/plus/signforinfo.php?id=[field:id/]'>
                                    详情
                                </a>
                                <span style="color:#A2A4AD; ">[field:pubdate function='strftime("%m-%d",@me)'/]</span>
                            </li>