<?php
$z[0]=Array("field","",143,162);
$z[0][4]['name']="title";
$z[1]=Array("global","",163,189);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",230,259);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",299,357);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",380,412);
$z[4][4]['filename']="h.htm";
$z[5]=Array("include","",472,507);
$z[5][4]['filename']="left.htm";
$z[6]=Array("global","",642,674);
$z[6][4]['name']="cfg_templets_skin";
$z[7]=Array("type","\r\n      [field:typename/]",830,890);
$z[7][4]['type']="self";
$z[8]=Array("field","",938,967);
$z[8][4]['name']="position";
$z[9]=Array("field","",1115,1143);
$z[9][4]['name']="content";
$z[10]=Array("include","",1170,1207);
$z[10][4]['filename']="footer.htm";

?>