<?php
$z[0]=Array("global","",391,416);
$z[0][4]['name']="cfg_cmsurl";
$z[1]=Array("global","",571,596);
$z[1][4]['name']="cfg_cmsurl";
$z[2]=Array("global","",740,765);
$z[2][4]['name']="cfg_cmsurl";
$z[3]=Array("global","",907,932);
$z[3][4]['name']="cfg_cmsurl";
$z[4]=Array("global","",1090,1115);
$z[4][4]['name']="cfg_cmsurl";
$z[5]=Array("global","",1258,1283);
$z[5][4]['name']="cfg_cmsurl";
$z[6]=Array("channel","\r\n      	<li><a href='[field:typeurl/]' class=\"bsa\" target=\"_blank\">[field:typename/]</a></li>\r\n      	",1593,1744);
$z[6][4]['typeid']="9";
$z[6][4]['row']="8";
$z[7]=Array("global","",2264,2289);
$z[7][4]['name']="cfg_cmsurl";
$z[8]=Array("global","",2511,2536);
$z[8][4]['name']="cfg_cmsurl";
$z[9]=Array("global","",2697,2722);
$z[9][4]['name']="cfg_cmsurl";
$z[10]=Array("global","",2881,2906);
$z[10][4]['name']="cfg_cmsurl";

?>