<?php
$z[0]=Array("field","",143,162);
$z[0][4]['name']="title";
$z[1]=Array("global","",163,189);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",230,259);
$z[2][4]['name']="keywords";
$z[3]=Array("global","",277,309);
$z[3][4]['name']="cfg_templets_skin";
$z[4]=Array("field","",412,470);
$z[4][4]['name']="description";
$z[4][4]['function']="html2text(@me)";
$z[5]=Array("include","",726,761);
$z[5][4]['filename']="head.htm";
$z[6]=Array("global","",954,986);
$z[6][4]['name']="cfg_templets_skin";
$z[7]=Array("type","\r\n      [field:typename/]",1150,1210);
$z[7][4]['type']="self";
$z[8]=Array("field","",1258,1287);
$z[8][4]['name']="position";
$z[9]=Array("list","\r\n      <li><img src=\"/images/arrl.png\" style=\"float:left; margin-top:9px; margin-right:5px;\"/><a href='[field:arcurl/]'>[field:title/]</a></li>\r\n      ",1419,1623);
$z[9][4]['pagesize']="20";
$z[9][4]['titlelen']="138";
$z[10]=Array("onduty","",1725,1753);
$z[11]=Array("pagelist","",1934,2005);
$z[11][4]['listitem']="info,index,end,pre,next,pageno";
$z[11][4]['listsize']="5";
$z[12]=Array("include","",2036,2073);
$z[12][4]['filename']="footer.htm";

?>